import type { Metadata } from "next";
import '../globals.css'

export const metadata: Metadata = {
  title: "HexAndCode",
  description: "Generated by create next app",
};

export default function LandingLayout({
  children,
}:any) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
